name: build
on:
  push:
    branches: master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
        architecture: [ 'x64' ]

    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          cache: maven

      - name: Build with Maven
        run: |
          mvn verify
        env:
          MAVEN_ARGS: --batch-mode --no-transfer-progress
